// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace zSkinCareBookingRepositories.Models;

public partial class BlogPost
{
    public int PostId { get; set; }

    public string Title { get; set; }

    public string Content { get; set; }

    public int? AuthorId { get; set; }

    public DateTime? PublishedDate { get; set; }

    public bool? IsPublished { get; set; }

    public string Slug { get; set; }

    public string MetaDescription { get; set; }

    public virtual ICollection<BlogCategory> Categories { get; set; } = new List<BlogCategory>();
}